kind = "mobile"
previewPath = "/"
title = "Maanak Vision"
version = "1.0.0"
id = "artifacts/maanak-vision"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25625

[services.development]
run = "pnpm --filter @workspace/maanak-vision run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/maanak-vision", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/maanak-vision", "run", "serve" ]

[services.env]
PORT = "25625"
BASE_PATH = "/"
